---
# Console logger
- descriptor: "pip-services-commons:logger:console:default:1.0"
  level: "trace"

# Performance counters that posts values to log
- descriptor: "pip-services-commons:counters:log:default:1.0"
  level: "trace"

# In-memory persistence. Use only for testing!
#- descriptor: "pip-services-msgtemplates:persistence:memory:default:1.0"

# File persistence. Use it for testing of for simple standalone deployments
- descriptor: "pip-services-msgtemplates:persistence:file:default:1.0"
  path: "./data/message_templates.json"

# MongoDB Persistence
# - descriptor: "pip-services-msgtemplates:persistence:mongodb:default:1.0"
#   collection: msgtemplates
#   connection:
#     host: localhost
#     port: 27017
#     database: test
#   credential:
#     username: test
#     password: pwd124

# Default controller
- descriptor: "pip-services-msgtemplates:controller:default:default:1.0"

# HTTP endpoint version 1.0
- descriptor: "pip-services-msgtemplates:service:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# Seneca endpoint version 1.0
# - descriptor: "pip-services-msgtemplates:service:seneca:default:1.0"
#   connection:
#     protocol: "tcp"
#     host: "0.0.0.0"
#     port: 8082
